"""OpenComp Conform — .nk script generator (pure string templating).

Nuke's .nk format is plain text key-value blocks.
One Read node + one Write node + Viewer per shot.
Auto-layout xpos/ypos so graph isn't spaghetti.
Frame padding: %04d
"""

import pathlib

_NK_HEADER = """# Nuke script generated by OpenComp Conform
# {shot_name}
version 13.2 v1
"""

_NK_READ = """Read {{
 inputs 0
 file "{filepath}"
 format "{width} {height} 0 0 {width} {height} 1 {shot_name}"
 first {first}
 last {last}
 origfirst {origfirst}
 origlast {origlast}
 name Read1
 xpos {xpos}
 ypos {ypos}
}}
"""

_NK_WRITE = """Write {{
 file "{filepath}"
 file_type exr
 first {first}
 last {last}
 name Write1
 xpos {xpos}
 ypos {ypos}
}}
"""

_NK_VIEWER = """Viewer {{
 frame_range {first}-{last}
 name Viewer1
 xpos {xpos}
 ypos {ypos}
}}
"""


def generate_nk(shot_name, plate_path, output_path,
                first_frame=1001, last_frame=1100,
                orig_first=None, orig_last=None,
                width=1920, height=1080):
    """Generate a .nk script string for a single shot.

    Args:
        shot_name: Shot identifier (e.g. "SH010").
        plate_path: Path to plate sequence (with %04d frame padding).
        output_path: Path for Write node output.
        first_frame: First frame of cut.
        last_frame: Last frame of cut.
        orig_first: First frame with handles (defaults to first_frame).
        orig_last: Last frame with handles (defaults to last_frame).
        width: Image width.
        height: Image height.

    Returns:
        .nk script as a string.
    """
    if orig_first is None:
        orig_first = first_frame
    if orig_last is None:
        orig_last = last_frame

    # Auto-layout: vertical stack
    read_x, read_y = 0, 0
    write_x, write_y = 0, 200
    viewer_x, viewer_y = 200, 200

    nk = _NK_HEADER.format(shot_name=shot_name)

    nk += _NK_READ.format(
        filepath=plate_path,
        width=width, height=height,
        shot_name=shot_name,
        first=first_frame, last=last_frame,
        origfirst=orig_first, origlast=orig_last,
        xpos=read_x, ypos=read_y,
    )

    nk += _NK_WRITE.format(
        filepath=output_path,
        first=first_frame, last=last_frame,
        xpos=write_x, ypos=write_y,
    )

    nk += _NK_VIEWER.format(
        first=first_frame, last=last_frame,
        xpos=viewer_x, ypos=viewer_y,
    )

    return nk


def export_nk_for_clip(clip, shot_dir, sequence="SEQ010"):
    """Generate and write a .nk script for a single clip.

    Args:
        clip: Clip dict from ingest.get_clips() (with handles if available).
        shot_dir: Shot directory path.
        sequence: Sequence name.

    Returns:
        Path to written .nk file.
    """
    shot_name = clip.get('clip_name', 'unknown')
    shot_dir = pathlib.Path(shot_dir)

    # Plate path with frame padding
    plate_pattern = f"{shot_name}.%04d.exr"
    plate_path = str(shot_dir / "plates" / plate_pattern)

    # Output path
    render_pattern = f"{shot_name}_comp.%04d.exr"
    output_path = str(shot_dir / "render" / render_pattern)

    # Frame range
    duration = clip.get('duration_frames', 100)
    head = clip.get('head_handles', 0)
    first_frame = 1001
    last_frame = first_frame + duration - 1
    orig_first = first_frame - head
    orig_last = last_frame + clip.get('tail_handles', 0)

    nk_content = generate_nk(
        shot_name=shot_name,
        plate_path=plate_path,
        output_path=output_path,
        first_frame=first_frame,
        last_frame=last_frame,
        orig_first=orig_first,
        orig_last=orig_last,
    )

    nk_path = shot_dir / f"{shot_name}_v001.nk"
    nk_path.write_text(nk_content)

    return nk_path
